### ISSUE TITLE
Slashes duplicated twice

### ISSUE THREAD

**Issue by giuseppe998e** [sdushantha/tmpmail#12]
https://github.com/sdushantha/tmpmail/blob/b65d55bbb34bb323d941b92bc125e681c0b20715/tmpmail#L25-L31

Should be
```bash
TMPMAIL_DIR="/tmp/tmpmail"

# TMPMAIL_EMAIL_ADDRESS is where we store the temporary email address 
# that gets generated. This prevents the user from providing  
# the email address everytime they run tmpmail 
TMPMAIL_EMAIL_ADDRESS="$TMPMAIL_DIR/email_address"
TMPMAIL_HTML_EMAIL="$TMPMAIL_DIR/tmpmail.html"
```

**Comment by rpdelaney** [comment]
In a POSIX filesystem this is not syntactically significant. `/foo/bar/` == `/foo////bar/`

**Comment by giuseppe998e** [comment]
> In a POSIX filesystem this is not syntactically significant. `/foo/bar/` == `/foo////bar/`

I know, it's just syntactically cleaner/correct.
