### ISSUE TITLE
body is not shown for plaintext mails

### ISSUE THREAD

**Issue by belzebub40k** [sdushantha/tmpmail#14]
If an email is only sent as plaintext the script does not show the output because the body is delivered in a different field.

```
{
	"id": 639,
	"from": "someone@example.com",
	"subject": "Some subject",
	"date": "2018-06-08 14:33:55",
	"attachments": [{
		"filename": "iometer.pdf",
		"contentType": "application\/pdf",
		"size": 47412
	}],
	"body": "Some message body\n\n",
	"textBody": "Some message body\n\n",
	"htmlBody": ""
}
```

See section **Fetching single message** under https://www.1secmail.com/api/

**Comment by sdushantha** [comment]
@belzebub40k The issue has been fixed in #16, thanks to @rjhbrunt

**Comment by belzebub40k** [comment]
Thanks but it solves the problem only partly. With _w3m_ the mails are not displayed correctly because `\n` is used for newlines in plaintext instead of `<br/>`. I suggest to add `<pre></pre>` around `HTML_BODY` if `textBody` is used.

`[ -z "$HTML_BODY" ] && HTML_BODY="<pre>$(jq -r ".textBody" <<<"$DATA")</pre>"`

**Comment by sdushantha** [comment]
@belzebub40k

**Comment by belzebub40k** [comment]
From https://www.w3schools.com/tags/tag_pre.asp

> The \<pre\> tag defines preformatted text.
> 
> Text in a \<pre\> element is displayed in a fixed-width font, and the text preserves both spaces and line breaks. The text will be displayed exactly as written in the HTML source code.

**Comment by sdushantha** [comment]
@belzebub40k I added the pre tags in the latest commit 6694ede

**Comment by belzebub40k** [comment]
Thanks, looks good now.
