### ISSUE TITLE
Enable TLD selection

### ISSUE THREAD

**Issue by frankenstein91** [sdushantha/tmpmail#17]
The provider 1secmail.com offers several TLDs for its service, I would also like to have this selection in the CLI.
Thanks a lot

**Comment by sdushantha** [comment]
I dont see the point of creating allowing the user to chose a TLD. `tmpmail` is supposed to be used a disposeable email tool, so the email TLD should not matter when you use it.

If you can provide a good reason for why it should be added, I will have a think about it.
But if you really want to be added, you can create a fork of this project

**Comment by frankenstein91** [comment]
did not see https://github.com/sdushantha/tmpmail/blob/c135fceb7ab1a729a19feadb8883d5730734e475/tmpmail#L81 should be okay
