### ISSUE TITLE
Could not resolve host: raw.githubusercontent.com

### ISSUE THREAD

**Issue by gcpmusic** [sdushantha/tmpmail#18]
I cant install it:

gCs-MacBook-Pro:~ gc$ curl -L "https://git.io/tmpmail" > tmpmail && chmod +x tmpmail
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0
curl: (6) Could not resolve host: raw.githubusercontent.com

Any help please?
Thank you in advance.

**Comment by sdushantha** [comment]
Hey @gcpmusic,

Try out this solution:
https://stackoverflow.com/a/24987376/9215267

If it doesnt work try doing a Google search because it is an issue with your computer and not `tmpmail`.

**Comment by gcpmusic** [comment]
Many thanx Siddharth Dushantha
I have soled it disabling DNSCrypt! just for the sake of someone else bumping in this issue.
All the best

**Comment by sdushantha** [comment]
@gcpmusic Thank you for telling us your solution :)
