### ISSUE TITLE
Email disappear!

### ISSUE THREAD

**Issue by gcpmusic** [sdushantha/tmpmail#20]
How long the received email will stay on the 1secmail server?
I noticed that after a bit is not present anymore. Would be good to know how long will be available.
Thanks

**Comment by aakash30jan** [comment]
1secmail's [Terms & Conditions ](https://www.1secmail.com/tac/) page says it's 1 hour. 

> All incoming emails temporarily stored on our Service are permanently deleted after 1 hour.
