### ISSUE TITLE
I created an AUR package

### ISSUE THREAD

**Issue by b12f** [sdushantha/tmpmail#3]
In case you want to document it: https://aur.archlinux.org/packages/tmpmail-git/

Also, if you want to maintain the PKGBUILD, hit me up and you can co-maintain or I'll even transfer the ownership to you.

**Comment by loki7990** [comment]
Do you need to have a `return 0` in the build function? Pretty sure you can remove the build function entirely

**Comment by sdushantha** [comment]
Thank you for creating an AUR package!

I unfortunately won't be able to maintain the package any time soon because I'm currently using macOS and won't be using Linux for a while. But once I get back onto my Linux machine I'll be more than happy to maintain the AUR package 😊

**Comment by sdushantha** [comment]
@b12f I have updated the README with installation options and mentioned the AUR package as being one of them.
