### ISSUE TITLE
shuf is not POSIX-compliant

### ISSUE THREAD

**Issue by ndalliard** [sdushantha/tmpmail#44]
You are using `shuf` which is not POSIX-compliant.

I found an answer/solution [on stackoverflow](https://stackoverflow.com/a/30133294).

It seems that the proposed solution is not the most performant, but because you are shuffling only 5 values, that shouldn't be a problem.

**Comment by sdushantha** [comment]
> You are using `shuf` which is not POSIX-compliant.

That's new to me, thank you for letting me know! I'll look into it when I get some time :)

**Comment by ndalliard** [comment]
I didn't knew it either. But I ran your script on OpenBSD and it doesn't have `shuf`. Thanks, take your time.

**Comment by sdushantha** [comment]
@ndalliard This has been fixed in #45 :)
