### ISSUE TITLE
Emails with multibyte chars not appearing due to column

### ISSUE THREAD

**Issue by dgeneratioN** [sdushantha/tmpmail#5]
Sent myself an email with the subject text containing the char "ê".

```
./tmpmail
[ Inbox for ehkrdfjqeka@1secmail.com ]

column: Invalid or incomplete multibyte or wide character
```
The email is then unreadable as well.

If you only include those especial characters in the email body then i can be read
```
./tmpmail -t -r
column: Invalid or incomplete multibyte or wide character
To: ehkrdfjqeka@1secmail.com
From: ------@gmail.com
Subject: aaaee

aaa?eeeeeee
```

where the ?='ê'

**Comment by sdushantha** [comment]
It works for me. I think it has to do with your locale
```console
$ bash tmpmail
[ Inbox for ouybycmahai@1secmail.org ]

84463978   example@example.com   hehehehê
```

**Comment by parth-io** [comment]
I am facing the same issue even though my locale setting for my terminal (bash) has UTF-8 encoding, which should be correct.

```
$ locale
LANG=en_SG.UTF-8 
LANGUAGE=en_SG:en
```

I checked this by running:
```
$ printf '\xC3\xAA'
ê
$ echo -e '\xC3\xAA'
ê
$ echo -e '\u00ea'
ê
```

Checking 1secmail's API, it gives the character ê in the Java/C++ escape sequence, i.e. u\00ea, but jq is able to interpret this as UTF-8.

Digging further, if I change line 187 of tmpmail  to `echo $INBOX` from `column -t -s "||" <<< "$INBOX" `, the output is:

```
$ tmpmail
[ Inbox for nfflkavazsg@1secmail.org ]

84563896 ||example@example.com ||hehehehê
```

This is expected as || is meant as a divider for `column`.

So I believe `echo` is able to render the character properly. I am looking at the source code of `column`, but I cannot figure out why it is causing this error, or if something else is wrong in tmpmail.

Any thoughts?

**Comment by sdushantha** [comment]
@parth-io  Could this be any help?
This in the first few lines in `tmpmail`. 

```bash
export LC_CTYPE=C 
export LANG=C
```

Which got changed to this today in #2 

```bash
export LC_ALL=C
export LC_CTYPE=C
```

Does the latest commit of `tmpmail`, with the new locale, fix your issue or maybe help you?

**Comment by parth-io** [comment]
Sadly, it doesn't work yet. For now, a workaround is just to redirect the output to a file.
`
(printf '%s\n' "${INBOX[@]}") > ./file.txt
`
For some reason, running the following line in tmpmail gives the same error, but when run in an independent script, it works beautifully with no error messages.
`column -t -s "||" < "./file.txt"`

Still scratching my head over why `column` does not work as expected in tmpmail, or on my system

**Comment by GReagle** [comment]
I can duplicate this problem.  However, when I remove the lines
export LC_ALL=C
export LC_CTYPE=C
from tmpfile, then I no longer have the problem.  Here is the result of my locale command:
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

Is it proper to set/change these variables at all?  Maybe they should be omitted from this script?

**Comment by sdushantha** [comment]
@GReagle 
> Maybe they should be omitted from this script?

Hmm...this is strange. I needed those lines because `tmpmail` would act up if I didn't have those lines. I think it was something to do with `column`.  But I just tried removing those lines now and `tmpmail` works perfectly without any problems. Not sure what the issue was.

I'll remove it for now 👍

**Comment by GReagle** [comment]
I think that this problem might be fixed now.

**Comment by parth-io** [comment]
You're absolutely right. Removing those lines fixes the issues. Great find.
