### ISSUE TITLE
New line

### ISSUE THREAD

**Issue by hpapagaj** [sdushantha/tmpmail#50]
For some reason when I generate new email, tmpmail doesn't output new line and my terminal is messed up:

<img width="573" alt="Screenshot 2021-01-11 at 20 06 37" src="https://user-images.githubusercontent.com/72989831/104226903-d1d97500-5448-11eb-8e7e-5878091769ab.png">

**Comment by hpapagaj** [comment]
As temp solution I modified code:

` [ "$EXTERNALLY" = true ] && cat "$TMPMAIL_EMAIL_ADDRESS" && echo "\n"`

<img width="410" alt="Screenshot 2021-01-11 at 20 14 34" src="https://user-images.githubusercontent.com/72989831/104227404-a3a86500-5449-11eb-9633-a9c191718894.png">

**Comment by sdushantha** [comment]
Thank you for letting me know about this issue. I have fixed this in the newest version of `tmpmail`
