### ISSUE TITLE
1secmail API does not support the following usernames:

### ISSUE THREAD

**Issue by mehtaarn000** [sdushantha/tmpmail#52]
- abuse
- webmaster
- contact
- postmaster
- hostmaster
- admin

See here:
![1secmail](https://user-images.githubusercontent.com/66114536/106856024-813dec00-6683-11eb-8eb4-26faaa49d353.png)

Maybe implement some Regex to prevent users from creating custom email addresses using these usernames?

**Comment by sdushantha** [comment]
Thank you for letting me know about this issue!

I have added a regex checking for blacklisted usernames with a detailed error message:
![Screenshot 2021-02-10 at 17 51 23](https://user-images.githubusercontent.com/27065646/107542631-ad4bf680-6bc8-11eb-8348-361576276e81.png)
