### ISSUE TITLE
tag releases

### ISSUE THREAD

**Issue by legendofmiracles** [sdushantha/tmpmail#58]
Hey! I packaged tmpmail for nixpkgs a while back, but just noticed that you also update this project more often and even release versions.
Unfortunately I cannot seem to find the appropriate tags for each version, which would make packaging - updating and maintaing the package a lot easier in nixpkgs

Cheers

**Comment by sdushantha** [comment]
I've created a release now :)
https://github.com/sdushantha/tmpmail/releases/tag/v1.1.4

**Comment by legendofmiracles** [comment]
Thank you, I opened a PR here:
https://github.com/NixOS/nixpkgs/pull/145278
