### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by bitcoinmeetups** [sdushantha/tmpmail#60]
Hello,

I'm MB. A very nice and polite guy.

Here is an error message I'm getting. Any way to work around it?

mkdir: cannot create directory ‘/tmp’: Read-only file system          ./tmpmail: 130: cannot create /tmp/tmpmail/email_address: Directory nonexistent
head: cannot open '/tmp/tmpmail/email_address' for reading: No such file or directory

**Comment by sdushantha** [comment]
I'm not entirely sure why you are getting that error. Seems like you have some permission issues on the /tmp directory. 

Try googling to fix this issue because it is not an issue with tmpmail but its an issue with your environment.
