### ISSUE TITLE
Error: Could not find 'w3m', is it installed? on macOS

### ISSUE THREAD

**Issue by lfaoro** [sdushantha/tmpmail#61]
```shell
$ curl -L "https://git.io/tmpmail" > /usr/local/bin/tmpmail && chmod +x /usr/local/bin/tmpmail
```

<img width="475" alt="image" src="https://user-images.githubusercontent.com/3834345/146228611-2a34d84c-6d97-4420-8db3-a69f2e11df40.png">

**Comment by sdushantha** [comment]
Have you made sure you have installed the dependencies? `w3m` is one of them.
