### ISSUE TITLE
Request for Pacstall Support

### ISSUE THREAD

**Issue by wizard-28** [sdushantha/tmpmail#63]
[Pacstall](https://github.com/pacstall/pacstall) is a community-driven AUR-like package manager for Ubuntu. We have an ongoing [pull request](https://github.com/pacstall/pacstall-programs/pull/579) to add tmpmail to our repository.

We have a few questions for you:
* Would you like to maintain the pacscript (similar to a PKGBUILD) yourself? We can maintain it for you if you decide not to.
* Could you include a section in your documentation showing Pacstall as a valid method of installation for tmpmail for Debian/Ubuntu users? We could make a pull request for that if you want.

**Comment by sdushantha** [comment]
This sounds great!

> Would you like to maintain the pacscript (similar to a PKGBUILD) yourself? We can maintain it for you if you decide not to.

I'd rather have you guys maintain it

> Could you include a section in your documentation showing Pacstall as a valid method of installation for tmpmail for Debian/Ubuntu users? We could make a pull request for that if you want.

Yes I'll include, just send a PR and I'll merge it right away :)
