### ISSUE TITLE
Unknown release commit

### ISSUE THREAD

**Issue by dusansimic** [sdushantha/tmpmail#71]
I'm maintaining AUR package for tmpmail ([link](https://aur.archlinux.org/packages/tmpmail)) and I've come across a small problem. The latest release (tag v1.2.0) points to a commit https://github.com/sdushantha/tmpmail/commit/3ba416b930e5d0379400a8bde710334c66dff3e6, however the version number in the source was not changed until https://github.com/sdushantha/tmpmail/commit/ec2d32147d28618cba4e36a0425c592bafcef864. I can also see that copying of the email address was introduced in https://github.com/sdushantha/tmpmail/commit/b28789b9eafe8141464493d898252c0438822150 as well as bumping the version number once again. I'm not sure which one should be used and weather this was deliberate or a mistake.

Thanks in advance!

**Comment by sdushantha** [comment]
Hey @dusansimic, I really appreciate you maintaining the AUR package!
You are correct, I did make a mistake. I have pushed a new commit and created a
new release which should hopefully fix this issue. 

Let me whether know if it works or not :+1:

**Comment by dusansimic** [comment]
Thanks for a quick response! Worked like a charm!
