### ISSUE TITLE
Is it possible to use another API with doing no change on script?

### ISSUE THREAD

**Issue by reo6** [sdushantha/tmpmail#77]
Hi!

1secmail service doesn't seem to be working very well, at least for me. It most of the time works but it has frequent down times. Was this script designed only for 1secmail's api or is there any other service it supports, or reported working with this script?

**Comment by reo6** [comment]
Sorry for the wrong issue. I couldn't find any button to remove the issue, please remove this. I think the problem was caused by the sender side.

**Comment by sdushantha** [comment]
Hi @reo6! This script was designed to only work with 1secmail's API. But feel free to fork it and create a version for an another temporary email service of your choice :)
