### ISSUE TITLE
"tr: Illegal byte sequence" on FreeBSD

### ISSUE THREAD

**Issue by rm1984** [sdushantha/tmpmail#8]
Hi,

the following line:

`USERNAME=$(head /dev/urandom | tr -dc a-z | cut -c1-11)`

returns the following error on FreeBSD:

`tr: Illegal byte sequence`

and no valid e-mail address can be generated.
I suggest to add the following line at the top of the script:

`export LC_ALL=C `

Thanks for the nice tool,
regards,
Riccardo

**Comment by sdushantha** [comment]
Thank you for letting me know. I have added your suggestion in b65d55b
